# Generated by Django 3.1.2 on 2021-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('claimed', 'claimed')], default='new', max_length=10),
        ),
    ]
