# Generated by Django 3.1.2 on 2021-06-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_number', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='value',
            field=models.IntegerField(default=10000),
        ),
    ]
