# Generated by Django 3.1.2 on 2021-04-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_number', '0002_serialnumber_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serialnumber',
            name='generated_count',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
