# Generated by Django 3.1.2 on 2021-05-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serial_number', '0003_auto_20210418_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='serialnumber',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('redeem', 'redeem')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='serialnumber',
            name='type',
            field=models.CharField(choices=[('new', 'new'), ('redeem', 'redeem')], default='new', max_length=10),
        ),
    ]
