# Generated by Django 3.1.2 on 2020-10-29 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimoni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimoni',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
