# Generated by Django 3.1.2 on 2020-10-18 03:38

from django.db import migrations, models
import sapujagad.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=sapujagad.core.utils.FilenameGenerator(prefix='team'))),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
                ('position', models.CharField(blank=True, max_length=254, null=True)),
                ('motto', models.CharField(blank=True, max_length=254, null=True)),
                ('fb_link', models.CharField(blank=True, max_length=254, null=True)),
                ('twitter', models.CharField(blank=True, max_length=254, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
