# Generated by Django 3.1.2 on 2022-04-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cashflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_jv', models.CharField(blank=True, max_length=100, null=True)),
                ('no_akun', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_akun', models.CharField(blank=True, max_length=100, null=True)),
                ('catatan', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai_asing', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_dep', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_proyek', models.CharField(blank=True, max_length=100, null=True)),
                ('no_jv', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
