# Generated by Django 3.1.2 on 2022-04-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashflow',
            options={'verbose_name_plural': 'Cashflow'},
        ),
    ]
