# Generated by Django 3.2 on 2022-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0002_auto_20220428_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashflow',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
