# Generated by Django 3.1.2 on 2020-12-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.TextField(blank=True, max_length=50, null=True)),
                ('oil_type', models.TextField(blank=True, max_length=50, null=True)),
                ('wallet_type', models.CharField(choices=[('gopay', 'Gopay'), ('ovo', 'OVO'), ('dana', 'Dana'), ('shopee_pay', 'ShopeePay')], max_length=10)),
                ('status', models.CharField(choices=[('new', 'Baru'), ('paid', 'Dibayar'), ('cancelled', 'Di Cancel')], default='new', max_length=10)),
            ],
        ),
    ]
