# Generated by Django 3.1.2 on 2020-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulir', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulir',
            old_name='agent_id',
            new_name='dealer_code',
        ),
        migrations.RemoveField(
            model_name='formulir',
            name='job',
        ),
        migrations.AddField(
            model_name='formulir',
            name='product_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formulir',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
