# Generated by Django 3.1.2 on 2020-12-26 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulir', '0002_auto_20201226_0739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formulir',
            old_name='product_no',
            new_name='product',
        ),
    ]
