# Generated by Django 3.1.2 on 2020-12-27 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulir', '0003_auto_20201226_0939'),
        ('formulir', '0002_remove_formulir_job'),
    ]

    operations = [
    ]
