# Generated by Django 3.1.2 on 2021-06-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_auto_20210627_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balance',
            old_name='value',
            new_name='balance',
        ),
        migrations.AddField(
            model_name='balance',
            name='credit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='balance',
            name='debit',
            field=models.IntegerField(default=0),
        ),
    ]
