# Generated by Django 3.1.2 on 2021-06-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_auto_20210627_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeem',
            name='nominal',
        ),
        migrations.AlterField(
            model_name='balance',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
