# Generated by Django 3.1.2 on 2021-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0004_auto_20210627_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Sukses')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='redeem',
            name='status',
            field=models.CharField(choices=[('new', 'Baru'), ('paid', 'Dibayar')], default='new', max_length=10),
        ),
    ]
