# Generated by Django 3.1.2 on 2021-06-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0005_auto_20210627_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
