# Generated by Django 3.1.2 on 2021-06-27 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0006_redeem_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redeem',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
