# Generated by Django 3.1.2 on 2021-07-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0007_auto_20210627_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='redeem',
            name='dealer_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='redeem',
            name='paid_datetime',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
