# Generated by Django 3.1.2 on 2021-07-19 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0009_redeem_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='datetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
