# Generated by Django 3.1.2 on 2020-10-18 03:38

from django.db import migrations, models
import sapujagad.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to=sapujagad.core.utils.FilenameGenerator(prefix='banner'))),
                ('img2', models.ImageField(blank=True, null=True, upload_to=sapujagad.core.utils.FilenameGenerator(prefix='banner'))),
                ('img3', models.ImageField(blank=True, null=True, upload_to=sapujagad.core.utils.FilenameGenerator(prefix='banner'))),
                ('title', models.CharField(blank=True, max_length=254, null=True)),
                ('date', models.DateField()),
                ('short_desc', models.CharField(blank=True, max_length=254, null=True)),
                ('long_desc', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
