# Generated by Django 3.1.2 on 2020-10-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201028_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='img3',
        ),
        migrations.AlterField(
            model_name='blog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is published'),
        ),
    ]
