# Generated by Django 3.1.2 on 2020-10-28 12:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201028_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 12, 32, 57, 572188, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
