# Generated by Django 3.1.2 on 2020-10-29 06:12

from django.db import migrations, models
import sapujagad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201028_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img1',
            field=models.ImageField(upload_to=sapujagad.core.utils.FilenameGenerator(prefix='banner'), verbose_name='img 300px 200px'),
        ),
    ]
