# Generated by Django 3.1.2 on 2020-10-25 06:13

from django.db import migrations, models
import sapujagad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='fa_icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=sapujagad.core.utils.FilenameGenerator(prefix='service')),
        ),
    ]
