# Generated by Django 3.1.2 on 2021-04-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
