# Generated by Django 3.1.2 on 2022-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('purchase_invoice_item', 'Purchase Invoice Item'), ('purchase_invoice_expense', 'Purchase Invoce Expense'), ('cash_flow', 'Cash Flow'), ('jv', 'JV'), ('sales', 'Sales')], max_length=100)),
                ('json_data', models.TextField(blank=True, null=True)),
                ('item_joined', models.IntegerField(blank=True, default=1, null=True)),
                ('response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('failed', 'Failed')], max_length=100)),
            ],
            options={
                'unique_together': {('key', 'data_type')},
            },
        ),
    ]
