# Generated by Django 3.1.2 on 2022-04-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='model',
            field=models.CharField(choices=[('PurchaseItem', 'PurchaseItem'), ('PurchaseExpense', 'PurchaseExpense'), ('Cashflow', 'Cashflow'), ('JV', 'JV'), ('Sales', 'Sales')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jsondata',
            unique_together={('key', 'model')},
        ),
        migrations.RemoveField(
            model_name='jsondata',
            name='data_type',
        ),
    ]
