# Generated by Django 3.1.2 on 2022-04-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0002_auto_20220425_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('failed', 'Failed')], default='new', max_length=100),
        ),
    ]
