# Generated by Django 3.1.2 on 2022-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0003_auto_20220425_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='model',
            field=models.CharField(choices=[('invoice', 'invoice'), ('purchaseinvoice', 'purchaseinvoice'), ('cashflow', 'cashflow'), ('jv', 'jv')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('success', 'Success'), ('failed', 'Failed')], default='new', max_length=100),
        ),
    ]
