# Generated by Django 3.1.2 on 2022-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0004_auto_20220428_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='type',
            field=models.CharField(choices=[('purchaseinvoice', 'purchaseinvoice'), ('cashflow', 'cashflow'), ('jv', 'jv'), ('invoice', 'invoice')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jsondata',
            name='model',
            field=models.CharField(choices=[('purchaseinvoice', 'purchaseinvoice'), ('cashflow', 'cashflow'), ('jv', 'jv'), ('invoice', 'invoice')], max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='jsondata',
            unique_together={('key', 'model', 'type')},
        ),
    ]
