# Generated by Django 3.1.2 on 2022-05-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0005_auto_20220428_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='model',
            field=models.CharField(choices=[('PurchaseInvoiceItem', 'PurchaseInvoiceItem'), ('PurchaseInvoiceExpense', 'PurchaseInvoiceExpense'), ('Cashflow', 'Cashflow'), ('JV', 'JV'), ('Invoice', 'Invoice')], max_length=100, null=True),
        ),
    ]
