# Generated by Django 3.2 on 2022-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jsondata', '0006_auto_20220506_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
