# Generated by Django 3.1.2 on 2020-10-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('order', models.IntegerField(default=0)),
                ('url', models.CharField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
