# Generated by Django 3.1.2 on 2020-10-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='url',
            new_name='multi_page_url',
        ),
        migrations.AddField(
            model_name='menu',
            name='one_page_url',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
