# Generated by Django 3.1.2 on 2020-10-29 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201029_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='multi_page_url',
        ),
    ]
