# Generated by Django 3.1.2 on 2022-04-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoice_item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseinvoiceitem',
            options={},
        ),
    ]
