# Generated by Django 3.2 on 2022-06-04 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoice_item', '0003_alter_purchaseinvoiceitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoiceitem',
            name='item_price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
