# Generated by Django 3.1.2 on 2020-10-25 06:53

from django.db import migrations, models
import sapujagad.core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='img_detail',
            field=models.ImageField(default='', upload_to=sapujagad.core.utils.FilenameGenerator(prefix='portfolio')),
            preserve_default=False,
        ),
    ]
