# Generated by Django 3.1.2 on 2020-10-25 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20201025_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='text_value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
