# Generated by Django 3.1.2 on 2022-04-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_faktur', models.CharField(blank=True, max_length=100, null=True)),
                ('no_pelanggan', models.CharField(blank=True, max_length=100, null=True)),
                ('id_pelanggan', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_pelanggan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_faktur', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=250, null=True)),
                ('id_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('no_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan_barang', models.CharField(blank=True, max_length=100, null=True)),
                ('kuantitas', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
