# Generated by Django 3.1.2 on 2022-04-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_jv', models.CharField(blank=True, max_length=100, null=True)),
                ('no_akun', models.CharField(blank=True, max_length=100, null=True)),
                ('tgl_jv', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_akun', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('debit', models.CharField(blank=True, max_length=250, null=True)),
                ('kredit', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_dep', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
