# Generated by Django 3.1.2 on 2022-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurhaseInvoiceExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tgl_faktur', models.CharField(blank=True, max_length=100, null=True)),
                ('no_purchase_invoice', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_pemasok', models.CharField(blank=True, max_length=100, null=True)),
                ('no_faktur_vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('no_akun_beban', models.CharField(blank=True, max_length=100, null=True)),
                ('nama_akun_beban', models.CharField(blank=True, max_length=100, null=True)),
                ('nilai_beban', models.CharField(blank=True, max_length=100, null=True)),
                ('item_id', models.CharField(blank=True, max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('qty', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cashflow',
            },
        ),
    ]
