# Generated by Django 3.1.2 on 2022-04-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoice_expense', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PurhaseInvoiceExpense',
            new_name='PurchaseInvoiceExpense',
        ),
    ]
