# Generated by Django 3.2 on 2022-05-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_invoice_expense', '0003_auto_20220430_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseinvoiceexpense',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
